name: Publish Docker Image

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - '.github/workflows/build.yml'
      - 'examples/*'
      - 'LICENSE'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - '.github/workflows/build.yml'
      - 'examples/*'
      - 'LICENSE'

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/wavy-cat/gobrainfuck:latest
